In [1]:
import numpy as np

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
list(range(0.4,10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [6]:
list(np.arange(.4,10.4,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [9]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [11]:
np.logspace(1,5,10,base=2)
# give 10 lograthimc data

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.zeros((3,4,2))
#  2 is shape for zero generations
# 3d data with 4X2

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [16]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
arr = np.ones((3,4))

In [21]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [24]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [25]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [30]:
arr1 = np.eye(5)
# identity matrix

In [31]:
import pandas as pd

In [32]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [33]:
np.random.rand(2,3)

array([[0.53010568, 0.28909334, 0.41086444],
       [0.48406846, 0.8179224 , 0.59463451]])

In [36]:
np.random.randn(2,3)
# mean is zero and std is 1

array([[ 0.14051898, -0.82501977, -0.3708932 ],
       [-1.00935303,  1.14794573, -1.38946006]])

In [38]:
arr2 = np.random.randint(1,5,(3,4))

In [39]:
arr2.size

12

In [40]:
arr2.shape

(3, 4)

In [42]:
arr2.reshape(6,2)

array([[3, 2],
       [3, 2],
       [4, 4],
       [1, 2],
       [2, 2],
       [1, 2]])

In [46]:
arr2.reshape(2,6)

array([[3, 2, 3, 2, 4, 4],
       [1, 2, 2, 2, 1, 2]])

In [47]:
arr1 = np.random.randint(1,10,(5,6))

In [48]:
arr1

array([[3, 3, 3, 5, 5, 3],
       [8, 1, 8, 5, 2, 8],
       [1, 3, 9, 7, 8, 7],
       [1, 8, 2, 3, 8, 7],
       [5, 3, 8, 9, 5, 6]])

In [49]:
arr1>8

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True, False, False]])

In [51]:
arr1[arr1>=8]

array([8, 8, 8, 9, 8, 8, 8, 8, 9])

In [52]:
arr1

array([[3, 3, 3, 5, 5, 3],
       [8, 1, 8, 5, 2, 8],
       [1, 3, 9, 7, 8, 7],
       [1, 8, 2, 3, 8, 7],
       [5, 3, 8, 9, 5, 6]])

In [53]:
arr1[0,[0,1]]

array([3, 3])

In [58]:
arr1[2:4,[2,3]]

array([[9, 7],
       [2, 3]])

In [59]:
arr1 = np.random.randint(1,3,(3,3))

In [60]:
arr1

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 2]])

In [61]:
arr2 = np.random.randint(1,3,(3,3))

In [62]:
arr2

array([[2, 1, 2],
       [2, 1, 1],
       [1, 1, 1]])

In [63]:
arr1+arr2

array([[4, 3, 3],
       [4, 3, 2],
       [3, 3, 3]])

In [68]:
arr1*arr2
# index wise

array([[4, 2, 2],
       [4, 2, 1],
       [2, 2, 2]])

In [69]:
# matrix multiplications
arr1@arr2

array([[ 9,  5,  7],
       [ 9,  5,  7],
       [10,  6,  8]])

In [70]:
arr1/arr2

array([[1. , 2. , 0.5],
       [1. , 2. , 1. ],
       [2. , 2. , 2. ]])

In [71]:
arr1/0

C:\Users\DELL\AppData\Local\Temp\ipykernel_9304\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [73]:
# Broadcasting

In [74]:
arr = np.zeros((3,4))

In [75]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [78]:
a = np.array([1,2,3,4])

In [81]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [84]:
b = np.array([[3,4,5]])

In [85]:
arr+b.T

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [88]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 1.        ],
       [1.41421356, 1.41421356, 1.        ],
       [1.41421356, 1.41421356, 1.41421356]])

In [89]:
np.log10(arr1)

array([[0.30103, 0.30103, 0.     ],
       [0.30103, 0.30103, 0.     ],
       [0.30103, 0.30103, 0.30103]])

In [90]:
np.exp(arr1)

array([[7.3890561 , 7.3890561 , 2.71828183],
       [7.3890561 , 7.3890561 , 2.71828183],
       [7.3890561 , 7.3890561 , 7.3890561 ]])

In [91]:
np.min(arr1)

1

In [92]:
np.max(arr1)

2