In [1]:
# sort , search and counting function

In [2]:
import numpy as np

In [7]:
arr = np.array([2,3,900,23,66,4,5,6])

In [8]:
np.sort(arr)

array([  2,   3,   4,   5,   6,  23,  66, 900])

In [10]:
np.searchsorted(arr,100)

8

In [11]:
arr1 = np.array([0,344,676,44,53,24,5,5,0,0,54])

In [12]:
np.count_nonzero(arr1)

8

In [13]:
len(arr1)

11

In [14]:
11-8

3

In [16]:
np.where(arr1 == 54)

(array([10], dtype=int64),)

In [19]:
np.extract(arr1 > 40,arr1)

array([344, 676,  44,  53,  54])

In [20]:
# numpy byte swapping

In [40]:
arr1

array([          0,  1476460544, -1543372800,   738197504,   889192448,
         402653184,    83886080,    83886080,           0,           0,
         905969664])

In [41]:
# arr1.byteswap(True)
# True is like inplace

In [42]:
arr1

array([          0,  1476460544, -1543372800,   738197504,   889192448,
         402653184,    83886080,    83886080,           0,           0,
         905969664])

In [43]:
a = np.copy(arr1)
# deep copy

In [44]:
a

array([          0,  1476460544, -1543372800,   738197504,   889192448,
         402653184,    83886080,    83886080,           0,           0,
         905969664])

In [47]:
b = arr1.view()
# shallow copy

In [48]:
b

array([          0,  1476460544, -1543372800,   738197504,   889192448,
         402653184,    83886080,    83886080,           0,           0,
         905969664])

In [49]:
b[0] = 109

In [50]:
b

array([        109,  1476460544, -1543372800,   738197504,   889192448,
         402653184,    83886080,    83886080,           0,           0,
         905969664])

In [51]:
# Matrix library

In [52]:
import numpy.matlib as nm

In [55]:
nm.ones((3,4))
# matrix is subclass of array

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [56]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [57]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [58]:
# Linear algebra

In [59]:
arr1 = np.random.randint([[2,3],[4,5]])

In [60]:
arr2 = np.random.randint([[5,3],[2,5]])

In [61]:
arr1

array([[1, 2],
       [3, 1]])

In [62]:
arr2

array([[1, 0],
       [1, 4]])

In [63]:
np.dot(arr1,arr2)

array([[3, 8],
       [4, 4]])

In [64]:
arr1@arr2

array([[3, 8],
       [4, 4]])