In [1]:
import numpy as np

In [2]:
# ARRAY MANIPULATION

In [3]:
arr = np.random.randint(1,10,(4,4))

In [4]:
arr

array([[5, 3, 9, 6],
       [4, 6, 6, 5],
       [6, 8, 5, 3],
       [3, 8, 1, 1]])

In [5]:
arr.reshape(8,2)

array([[5, 3],
       [9, 6],
       [4, 6],
       [6, 5],
       [6, 8],
       [5, 3],
       [3, 8],
       [1, 1]])

In [6]:
arr.T

array([[5, 4, 6, 3],
       [3, 6, 8, 8],
       [9, 6, 5, 1],
       [6, 5, 3, 1]])

In [7]:
arr.flatten()

array([5, 3, 9, 6, 4, 6, 6, 5, 6, 8, 5, 3, 3, 8, 1, 1])

In [10]:
np.expand_dims(arr,axis=1)

array([[[5, 3, 9, 6]],

       [[4, 6, 6, 5]],

       [[6, 8, 5, 3]],

       [[3, 8, 1, 1]]])

In [11]:
np.expand_dims(arr,axis=0)

array([[[5, 3, 9, 6],
        [4, 6, 6, 5],
        [6, 8, 5, 3],
        [3, 8, 1, 1]]])

In [13]:
data = np.array([[1],[2],[3]])

In [14]:
np.squeeze(data)

array([1, 2, 3])

In [15]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [17]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [18]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [19]:
# Numpy Binary operation

In [20]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [21]:
arr1

array([[6, 7, 8, 2],
       [2, 1, 1, 6],
       [3, 7, 1, 4]])

In [22]:
arr2

array([[1, 7, 1, 5],
       [7, 5, 6, 9],
       [7, 6, 1, 2]])

In [23]:
arr1 + arr2

array([[ 7, 14,  9,  7],
       [ 9,  6,  7, 15],
       [10, 13,  2,  6]])

In [24]:
arr1 * arr2

array([[ 6, 49,  8, 10],
       [14,  5,  6, 54],
       [21, 42,  1,  8]])

In [25]:
arr1 / arr2

array([[6.        , 1.        , 8.        , 0.4       ],
       [0.28571429, 0.2       , 0.16666667, 0.66666667],
       [0.42857143, 1.16666667, 1.        , 2.        ]])

In [26]:
arr1 - arr2

array([[ 5,  0,  7, -3],
       [-5, -4, -5, -3],
       [-4,  1,  0,  2]])

In [27]:
# index wise power 
arr1**arr2

array([[       6,   823543,        8,       32],
       [     128,        1,        1, 10077696],
       [    2187,   117649,        1,       16]])

In [29]:
~arr1
# negation

array([[-7, -8, -9, -3],
       [-3, -2, -2, -7],
       [-4, -8, -2, -5]])

In [30]:
arr1>arr2

array([[ True, False,  True, False],
       [False, False, False, False],
       [False,  True, False,  True]])

In [31]:
# string operation

In [34]:
arr = np.array(['Anirudhra','Krish'])

In [35]:
arr

array(['Anirudhra', 'Krish'], dtype='<U9')

In [37]:
np.char.upper(arr)

array(['ANIRUDHRA', 'KRISH'], dtype='<U9')

In [38]:
np.char.capitalize(arr)

array(['Anirudhra', 'Krish'], dtype='<U9')

In [39]:
np.char.title(arr)

array(['Anirudhra', 'Krish'], dtype='<U9')

In [41]:
# Numpy mathematical functions

In [42]:
arr1

array([[6, 7, 8, 2],
       [2, 1, 1, 6],
       [3, 7, 1, 4]])

In [43]:
np.sin(arr1)

array([[-0.2794155 ,  0.6569866 ,  0.98935825,  0.90929743],
       [ 0.90929743,  0.84147098,  0.84147098, -0.2794155 ],
       [ 0.14112001,  0.6569866 ,  0.84147098, -0.7568025 ]])

In [44]:
np.cos(arr1)

array([[ 0.96017029,  0.75390225, -0.14550003, -0.41614684],
       [-0.41614684,  0.54030231,  0.54030231,  0.96017029],
       [-0.9899925 ,  0.75390225,  0.54030231, -0.65364362]])

In [45]:
np.tan(arr1)

array([[-0.29100619,  0.87144798, -6.79971146, -2.18503986],
       [-2.18503986,  1.55740772,  1.55740772, -0.29100619],
       [-0.14254654,  0.87144798,  1.55740772,  1.15782128]])

In [46]:
np.log10(arr1)

array([[0.77815125, 0.84509804, 0.90308999, 0.30103   ],
       [0.30103   , 0.        , 0.        , 0.77815125],
       [0.47712125, 0.84509804, 0.        , 0.60205999]])

In [47]:
np.exp(arr1)

array([[4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 7.38905610e+00],
       [7.38905610e+00, 2.71828183e+00, 2.71828183e+00, 4.03428793e+02],
       [2.00855369e+01, 1.09663316e+03, 2.71828183e+00, 5.45981500e+01]])

In [48]:
np.power(arr1,2)

array([[36, 49, 64,  4],
       [ 4,  1,  1, 36],
       [ 9, 49,  1, 16]], dtype=int32)

In [49]:
np.mean(arr1)

4.0

In [50]:
np.median(arr1)

3.5

In [53]:
np.std(arr1)

2.5495097567963922

In [54]:
np.var(arr1)

6.5

In [57]:
np.min(arr1)

1

In [56]:
np.max(arr1)

8

In [58]:
# Arithmetic operation in numpy

In [59]:
arr1

array([[6, 7, 8, 2],
       [2, 1, 1, 6],
       [3, 7, 1, 4]])

In [60]:
arr2

array([[1, 7, 1, 5],
       [7, 5, 6, 9],
       [7, 6, 1, 2]])

In [61]:
arr1 - arr2

array([[ 5,  0,  7, -3],
       [-5, -4, -5, -3],
       [-4,  1,  0,  2]])

In [62]:
np.subtract(arr1,arr2)

array([[ 5,  0,  7, -3],
       [-5, -4, -5, -3],
       [-4,  1,  0,  2]])

In [63]:
np.mod(arr1,arr2)

array([[0, 0, 0, 2],
       [2, 1, 1, 6],
       [3, 1, 0, 0]])

In [64]:
np.power(arr1,arr2)

array([[       6,   823543,        8,       32],
       [     128,        1,        1, 10077696],
       [    2187,   117649,        1,       16]])

In [65]:
np.sqrt(arr1)

array([[2.44948974, 2.64575131, 2.82842712, 1.41421356],
       [1.41421356, 1.        , 1.        , 2.44948974],
       [1.73205081, 2.64575131, 1.        , 2.        ]])

In [66]:
# Statistical function in numpy

In [67]:
arr1

array([[6, 7, 8, 2],
       [2, 1, 1, 6],
       [3, 7, 1, 4]])

In [68]:
np.mean(arr1)

4.0

In [69]:
np.std(arr1)

2.5495097567963922

In [70]:
np.median(arr1)

3.5